### ISSUE TITLE
 ./install_tilp.sh fails on OSX Ventura 13.3

### ISSUE THREAD

**Issue by spkrsmfx** [debrouxl/tilp_and_gfm#63]
When trying to compile on OSX Venture 13.3 ARM64, the compilation fails with the message:

dusb_vpkt.cc:368:35: error: invalid use of non-static data member 'data'
        if (size > sizeof(DUSBRawPacket::data) + 1)
                          ~~~~~~~~~~~~~~~^~~~
dusb_vpkt.cc:371:32: error: invalid use of non-static data member 'data'
                size = sizeof(DUSBRawPacket::data) + 1;
                              ~~~~~~~~~~~~~~~^~~~
2 errors generated.
make[4]: *** [libticalcs2_la-dusb_vpkt.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by adriweb** [comment]
That... is unexpected. Works fine here, although I'm testing on intel, but I should be able to test that later on arm64 (it's not like this language rule should be any different though!)

What's your compiler and its version, exactly?

**Comment by spkrsmfx** [comment]
sh-3.2# g++ --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by adriweb** [comment]
right, same here... might be a difference in the default compile flags, then, huh.
